### PR TITLE
more OS-group contributions

### PR DESCRIPTION
**Pull request by schirmeier**

### CODE REVIEW

**Comment by waehlisch** [comment]
@schirmeier, can you rebase?

**Comment by schirmeier** [comment]
I have no idea why CI fails here. Running init_site.py and init_readme.py works for me. Please investigate. :-)

**Comment by waehlisch** [comment]
> I have no idea why CI fails here. Running init_site.py and init_readme.py works for me. Please investigate. :-)

same, no clue, but we are looking into it. probably some toolchain hassle.

(thanks, and sorry, for being a guinea pig. previous tests didn't have this problem.)

**Comment by adeveloper-wq** [comment]
I pushed a fix on to `main` and tested it here: https://github.com/tud-cs/oss-collection/pull/5

Unfortunately, we forgot to test PRs opened by forks, which was the cause of the bug. The workflow should™ now also work on PRs triggered by forks.

@schirmeier, can you rebase? Sorry for the inconvenience!

**Pull request merged**
